spring.application.name=backend-fal
spring.datasource.url=jdbc:postgresql://localhost:5432/faldb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
pring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fortunetellapp@gmail.com
spring.mail.password=vote rnkk lqfe lhbv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=fortuneeTellJwtSecretKey2026VerySecureRandomKey12345
app.jwt.expiration=86400000

app.verification.code-expiration-minutes=10

server.port=8080